#!/bin/bash
# =============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of Flight Inventory.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight Inventory is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Inventory. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight Inventory, please visit:
# https://github.com/openflighthpc/flight-inventory
# ==============================================================================
initial_env=$(env)
alces_INSTALL_DIR="${alces_INSTALL_DIR:-/opt/flight/tools}"
alces_VERSION="${alces_VERSION:-2019.1.0}"

#==============================================================================
# DON'T EDIT ANYTHING UNDER HERE
#==============================================================================

# Check for Flight Core
if [ ! -x /opt/flight/bin/bundle ]; then
    echo "Unable to install; no Flight Core environment was found."
    exit 1
fi


# Detect whether script is being curled or run locally from within `scripts` directory
SCRIPT_PARENT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT_BASE=$(basename $SCRIPT_PATH)

if [[ $SCRIPT_BASE != "scripts" ]] ; then
    CLONE=true
    CHECKOUT=true
else
    CLONE=""
    alces_INSTALL_DIR=$SCRIPT_PARENT_PATH
    # Check if alces_VERSION was specified on CLI
    if echo "$initial_env" |grep -q '^alces_VERSION' ; then
        CHECKOUT=true
    else
        CHECKOUT=""
    fi
fi

# Create install dir
mkdir -p $alces_INSTALL_DIR
cd $alces_INSTALL_DIR

if [ ! -z $CLONE ] ; then
    # Install tool
    git clone https://github.com/openflighthpc/inventoryware
fi

cd inventoryware

if [ ! -z $CHECKOUT ] ; then
    git checkout $alces_VERSION
fi

# Install dependencies
flexec bundle install --path=vendor --without development test

# Setup command file
cat << EOF > /opt/flight/libexec/commands/inventory
: '
: NAME: inventory
: SYNOPSIS: A tool for collecting and parsing cluster inventory data
: VERSION: $alces_VERSION
: '
# =============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of Flight Inventory.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight Inventory is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Inventory. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight Inventory, please visit:
# https://github.com/openflighthpc/flight-inventory
# ==============================================================================
cd $alces_INSTALL_DIR/inventoryware
export FLIGHT_PROGRAM_NAME="\${flight_NAME} \$(basename \$0)"
flexec bundle exec bin/inventory "\$@"
EOF
